ALTER TABLE bookings ADD COLUMN IF NOT EXISTS source VARCHAR(255) DEFAULT 'Direct';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS package_name VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS special_requests TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS preferences TEXT;
