"""Add gst_number to bookings and checkouts

Revision ID: 33584694f076
Revises: 9ccb8b3c95d4
Create Date: 2026-06-21 19:37:37.511139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33584694f076'
down_revision: Union[str, Sequence[str], None] = '9ccb8b3c95d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('checkouts', sa.Column('gst_number', sa.String(), nullable=True))
    op.drop_index(op.f('ix_pricing_calendar_end_date'), table_name='pricing_calendar')
    op.drop_index(op.f('ix_pricing_calendar_id'), table_name='pricing_calendar')
    op.drop_index(op.f('ix_pricing_calendar_start_date'), table_name='pricing_calendar')
    op.drop_table('pricing_calendar')
    op.create_unique_constraint('_name_branch_uc', 'account_groups', ['name', 'branch_id'])
    op.create_unique_constraint('_ledger_name_branch_uc', 'account_ledgers', ['name', 'branch_id'])
    op.drop_constraint(op.f('checkouts_booking_id_key'), 'checkouts', type_='unique')
    op.drop_constraint(op.f('checkouts_package_booking_id_key'), 'checkouts', type_='unique')
    op.drop_constraint(op.f('food_orders_table_id_fkey'), 'food_orders', type_='foreignkey')
    op.create_foreign_key(None, 'food_orders', 'restaurant_tables', ['table_id'], ['id'])
    op.drop_constraint(op.f('uix_inventory_category_name'), 'inventory_categories', type_='unique')
    op.create_unique_constraint('uix_inventory_category_name_branch', 'inventory_categories', ['name', 'branch_id'])
    op.drop_constraint(op.f('uix_inventory_item_barcode'), 'inventory_items', type_='unique')
    op.drop_constraint(op.f('uix_inventory_item_code'), 'inventory_items', type_='unique')
    op.drop_constraint(op.f('uix_inventory_item_name'), 'inventory_items', type_='unique')
    op.create_unique_constraint('uix_inventory_item_barcode_branch', 'inventory_items', ['barcode', 'branch_id'])
    op.create_unique_constraint('uix_inventory_item_code_branch', 'inventory_items', ['item_code', 'branch_id'])
    op.create_unique_constraint('uix_inventory_item_name_branch', 'inventory_items', ['name', 'branch_id'])
    op.create_index(op.f('ix_restaurant_tables_branch_id'), 'restaurant_tables', ['branch_id'], unique=False)
    op.create_index(op.f('ix_restaurant_tables_id'), 'restaurant_tables', ['id'], unique=False)
    op.create_foreign_key(None, 'restaurant_tables', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(op.f('service_requests_table_id_fkey'), 'service_requests', type_='foreignkey')
    op.create_foreign_key(None, 'service_requests', 'restaurant_tables', ['table_id'], ['id'])
    op.alter_column('working_logs', 'clock_in_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('working_logs', 'clock_out_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkouts', 'gst_number')
    op.drop_column('bookings', 'gst_number')
    op.alter_column('working_logs', 'clock_out_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('working_logs', 'clock_in_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.create_foreign_key(op.f('service_requests_table_id_fkey'), 'service_requests', 'restaurant_tables', ['table_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'restaurant_tables', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_tables_id'), table_name='restaurant_tables')
    op.drop_index(op.f('ix_restaurant_tables_branch_id'), table_name='restaurant_tables')
    op.drop_constraint('uix_inventory_item_name_branch', 'inventory_items', type_='unique')
    op.drop_constraint('uix_inventory_item_code_branch', 'inventory_items', type_='unique')
    op.drop_constraint('uix_inventory_item_barcode_branch', 'inventory_items', type_='unique')
    op.create_unique_constraint(op.f('uix_inventory_item_name'), 'inventory_items', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_inventory_item_code'), 'inventory_items', ['item_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_inventory_item_barcode'), 'inventory_items', ['barcode'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uix_inventory_category_name_branch', 'inventory_categories', type_='unique')
    op.create_unique_constraint(op.f('uix_inventory_category_name'), 'inventory_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'food_orders', type_='foreignkey')
    op.create_foreign_key(op.f('food_orders_table_id_fkey'), 'food_orders', 'restaurant_tables', ['table_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('checkouts_package_booking_id_key'), 'checkouts', ['package_booking_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('checkouts_booking_id_key'), 'checkouts', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('_ledger_name_branch_uc', 'account_ledgers', type_='unique')
    op.drop_constraint('_name_branch_uc', 'account_groups', type_='unique')
    op.create_table('pricing_calendar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_calendar_pkey'))
    )
    op.create_index(op.f('ix_pricing_calendar_start_date'), 'pricing_calendar', ['start_date'], unique=False)
    op.create_index(op.f('ix_pricing_calendar_id'), 'pricing_calendar', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_calendar_end_date'), 'pricing_calendar', ['end_date'], unique=False)
    # ### end Alembic commands ###
